version: "3.9"

services:
  caddy:
    image: coloradostark/caddy-ssl-multisite:0.21
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www-data:/var/www
  php-server:
    image: php:7.4.13-fpm-alpine
    restart: always
    volumes:
      - www-data:/var/www
  node-server:
    image: node:14.15.3-alpine3.12
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - node-app:/home/node/app
    expose:
      - "8080"
    command: "npm start"
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - db-variables.env
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    env_file:
      - wp-variables.env
    volumes:
      - ./wp-content:/var/www/html/wp-content     
volumes:
  www-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./www-data"
  node-app:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./node-app"
  db_data: {}
