version: "2"

services:
  caddy:
    image: coloradostark/caddy-ssl-multisite
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - www-data:/var/www
  php-server:
    image: php:7.4.13-fpm-alpine
    restart: always
    volumes:
      - www-data:/var/www
volumes: www-data:${pwd}
