version: "3"

services:
  caddy:
    image: coloradostark/caddy-ssl-multisite:0.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www-data:/var/www
  php-server:
    image: php:7.4.13-fpm-alpine
    restart: always
    volumes:
      - ./www-data:/var/www
volumes:
  www-data:
